SCALRCORE-10952 Fix testsute on Windows
Scalr/kombu pull request #6
Opened 2019-02-04 11:09 UTC by danikmil

2019-02-04 20:16 UTC, maratkomarov requested changes

2019-02-04 20:16 UTC, maratkomarov commented on t/unit/transport/test_pyamqp.py
> +        assert 'm' in self.channel.no_ack_consumers
@danikmil почему такой фикс? тут случайно не распад строки в список `('m', 'y', '-', 'c' ....)` ?

2019-02-05 08:49 UTC, danikmil commented on t/unit/transport/test_pyamqp.py
> +        assert 'm' in self.channel.no_ack_consumers
@maratkomarov Да, але згідно структури тесту, то повертається лише перший елемент

2019-02-05 23:52 UTC, maratkomarov commented on t/unit/transport/test_pyamqp.py
> +        assert 'm' in self.channel.no_ack_consumers
@danikmil погоди, но тест же пассится на Linux без изменений, или как? Очень подозрительно. Это consumer tag, по нему вся иденитификация подписчика идет. Если мы тут нахимичим, очень дорого обойдется. Давай завтра пару минут голосом на стендапе пообщаемся.

2019-02-06 12:59 UTC, danikmil commented on t/unit/transport/test_pyamqp.py
> +        assert 'm' in self.channel.no_ack_consumers
@maratkomarov Гарне зауваження

2019-02-21 16:35 UTC, maratkomarov approved these changes

2019-02-21 16:35 UTC, merged